DL_DIR = "${TOPDIR}/../../external/meta-rcar-demo/work_v4hsbc_xen/yocto/common_data/downloads"
SSTATE_DIR = "${TOPDIR}/../../external/meta-rcar-demo/work_v4hsbc_xen/yocto/common_data/sstate"

SYSTEMD_AUTO_ENABLE:kuksa-databroker = "disable"
SYSTEMD_AUTO_ENABLE:kuksa-can-provider = "disable"
SYSTEMD_AUTO_ENABLE:agl-vss-helper = "disable"
SYSTEMD_AUTO_ENABLE:can-dev-helper = "disable"
SYSTEMD_AUTO_ENABLE:tbtnavi = "disable"
SYSTEMD_AUTO_ENABLE:pipewire = "disable"

IMAGE_INSTALL:remove = "agl-compositor-init-pipewire weston-pipewire"
